### ISSUE TITLE
bundle.watch tends to crash when a watched file is deleted

### ISSUE THREAD

**Issue by senritsu** [dowjones/gulp-bundle-assets#61]
On deleting any file or folder in the watched set, usually the bundle.watch crashes with the following error message:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch EPERM
  at errnoException (fs.js:1031:11)
  at FSEvent.FSWatcher._handle.onchange (fs.js:1049:26)

Process terminated with code 8.
```

Error message suggests it is a permission problem (which is not the case), and makes it seem like it is on the node fs side, but could be caught and handled by the bundle watcher

**Comment by chmontgomery** [comment]
Can you post your gulpfile, OS, version of gulp?

Also, since `bundle.watch` is simply using `gulp.watch` under the covers, do any of these help you?
* https://github.com/gulpjs/gulp/issues/738
* https://github.com/gulpjs/gulp/issues/660
* http://stackoverflow.com/questions/18634971/node-watch-eperm-when-the-watched-folder-is-deleted

**Comment by senritsu** [comment]
gulpfile, not sure if i am allowed to post it publicly, company policy and all that.

OS is windows 8.1 x64, local filesystem, full admin permissions
gulp dependency is ^3.8.10

removing a leading dot from the glob, or changing
```
**/*
```
to
```
**/*.*
```
had no effect. Still got a crash after deleting 2 or 3 files.

**Comment by vinhnghi223** [comment]
Any news on this? I have the same problem.
